[workspace]
members = [
    "test-client",
    "bson",
    "wasm",
    "byte-sequence",
    "json-like/json-like",
    "json-like/json-like-indent",
    "json-like/value",
]

[profile.release]
lto = true
opt-level = "s"