[package]
name = "bson"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "bson.rs"

[dependencies]
format-galaxy-core = { path = "../../core" }
bson = "1.0"
serde_json = "1.0"
anyhow = "1.0"